version: '3'

services:
  bedrock_server:
    image: bedrock_server:1.11.2.1
    build: .
    container_name: bedrock_server
    ports:
      - 19132:19132/udp
      - 19133:19133/udp
    stdin_open: true
    tty: true
    volumes:
      - ./data/worlds:/srv/bedrock_server/worlds
      - ./data/config:/srv/bedrock_server/config

    # override the default entrypoint to include access to a bash terminal for debugging.
    # entrypoint: bash -c "/srv/bedrock_server/startup.sh && /bin/bash"
